# Generated by Django 5.1.5 on 2025-03-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.company'),
        ),
    ]
