# Generated by Django 5.1.5 on 2025-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_chathistory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Completed', 'Completed')], default='Open', max_length=20),
        ),
    ]
