# Generated by Django 5.1.5 on 2025-03-25 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chathistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='company',
            field=models.ForeignKey(default='Untitled Company', on_delete=django.db.models.deletion.CASCADE, to='chatbot.company'),
        ),
    ]
