# Generated by Django 5.1.5 on 2025-03-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_sellmateagentchathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellmateagentchathistory',
            options={'ordering': ['timestamp']},
        ),
    ]
